#!/usr/bin/env bash

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom header to Nginx configuration
sudo sed -i '/http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
