#!/bin/bash
if [ -e /tmp/my_first_directory/betty ]; then
    rm /tmp/my_first_directory/betty
    echo "File has been deleted"
else
    echo "/tmp/my_first_directory/betty: cannot open '/tmp/my_first_directory/betty' (No such file or directory)"
fi
