#!/usr/bin/ env bash

# Define variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f ~/.ssh/$KEY_NAME -N $PASSPHRASE

echo "RSA key pair created with the name '$KEY_NAME' and protected by the passphrase."
